# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['hello_world']

# Cell

def hello_world(world):
    """
    This function says hello to the `world`
    """
    print("hello ", world)